swagger: '2.0'
info:
  title: Reactions microservice
  description: Operations to menage reactions
  version: 1.0.0
host: 127.0.0.1
schemes:
  - http
  - https
paths:
  /reactions/{story_id}:
    get:
      description: Return the list of reactions of a given story
      operationId: getReactions
      produces:
        - application/json
      parameters:
        - in: path
          name: story_id
          type: integer
          required: True
      responses:
        '200':
          description: A JSON array of JSON objects containing reactions data
          schema:
            type: array
            items:
              $ref: '#/definitions/reactions'
  /counters/{story_id}:
    get:
      description: Return the list of counters of the given story
      operationId: getCounters
      produces:
        - application/json
      parameters:
        - in: path
          name: story_id
          type: integer
          required: True
      responses:
        '200':
          description: A JSON array of JSON objects containing counters data
          schema:
            type: array
            items:
              $ref: '#/definitions/story'
  /new:
    post:
      description: Initializie a new counter when a new story has been published
      operationId: newStory
      consumes:
        - application/json
      parameters:
        - in: body
          name: story_id
          schema:
            $ref: '#/definitions/story'
      produces:
        - application/json
      responses:
        '200':
          description: Counters created successfully
  /react:
    post:
      description: Insert a new reaction
      operationId: react
      consumes:
        - application/json
      parameters:
        - in: body
          name: story_id
          schema:
            items:
              $ref: '#/definitions/react'
          required: True
          description: The value that identifies the story
      produces:
        - application/json
      responses:
        '200':
          description: Reaction submitted
  /delete:
    delete:
      description: Delete all the counters and the reactions of the given story
      operationId: delete
      consumes:
        - application/json
      parameters:
        - in: body
          name: story_id
          schema:
            items:
              $ref: '#/definitions/delete'
          required: True
          description: The value that identifies the story
      produces:
        - application/json
      responses:
        '200':
          description: Deletion has been successful

  /reactions/stats/{story_id}:
    get:
      description: Get reactions counter for a story
      operationId: statsReactions
      consumes:
        - application/json
      parameters:
        - in: path
          name: story_id
          required: True
          type: integer
          description: The value that identifies the story
      produces:
        - application/json
      responses:
        '200':
          description: Counters of reactions for a story

  /reactions/stats/users/{user_id}:
    get:
      description: Get reactions statistics for user wall
      operationId: statsUserReactions
      consumes:
        - application/json
      parameters:
        - in: path
          name: user_id
          required: True
          type: integer
          description: The value that identifies the user
      produces:
        - application/json
      responses:
        '200':
          description: Return reactions statistics for user's wall
        '400':
          description: There was an error calling stories service


definitions:
  reactions:
    type: object
    properties:
      id:
        type: integer
      reactor_id:
        type: integer
      story_id:
        type: integer
      reaction_type_id:
        type: integer
      reaction_type:
        type: integer
      marked:
        type: integer

  counters:
    type: object
    properties:
      reaction_type_id:
        type: integer
      story_id:
        type: integer
      counter:
        type: integer

  story:
    type: object
    properties:
      story_id:
        type: string

  react:
    type: object
    properties:
      story_id:
        type: integer
      current_user:
        type: integer
      reaction_caption:
        type: string

  delete:
    type: object
    properties:
      story_id:
        type: integer